include:
  - template: Auto-DevOps.gitlab-ci.yml

Docker Hub:
  stage: deploy
  script:
    - docker build --squash -t "lthn/vpn" .
    - docker push "lthn/vpn"
  environment:
    name: docker.io
  only:
    - master