build:
  stage: build
  script:
    - echo "appy days"

linux:
  stage: build
  image: node:16-bullseye-slim
  before_script:
    - apt update && apt install -y curl unzip
    - curl -fsSL https://deno.land/x/install/install.sh | sh
  script:
    - npm run server:build:linux
  artifacts:
    name: linux
    paths:
      - build/lthn

macos-arm64:
  stage: build
  image: node:16-bullseye-slim
  before_script:
    - apt update && apt install -y curl unzip
    - curl -fsSL https://deno.land/x/install/install.sh | sh
  script:
    - npm run server:build:macos-arm
  artifacts:
    name: macos
    paths:
      - build/lthn

macos-intell:
  stage: build
  image: node:16-bullseye-slim
  before_script:
    - apt update && apt install -y curl unzip
    - curl -fsSL https://deno.land/x/install/install.sh | sh
  script:
    - npm run server:build:macos-intell
  artifacts:
    name: macos
    paths:
      - build/lthn

windows:
  stage: build
  image: node:16-bullseye-slim
  before_script:
    - apt update && apt install -y curl unzip
    - curl -fsSL https://deno.land/x/install/install.sh | sh
  script:
    - npm run server:build:windows
  artifacts:
    name: windows
    paths:
      - build/lthn.exe
