include:
  - template: Auto-DevOps.gitlab-ci.yml

Docker Hub:
  stage: deploy
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - make build
    - make push
  environment:
    name: docker.io
  only:
    - master

build:
  stage: build
  image: lthn/build
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - make build
    - make push
