include:
  - template: Auto-DevOps.gitlab-ci.yml

Docker Hub:
  stage: deploy
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t lthn/vpn src
    - docker push lthn/vpn
  environment:
    name: docker.io
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      changes:
        - src/*

build:
  stage: build
  image: lthn/build
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE src
    - docker push $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      changes:
        - src/*

pages:
  image: python:3.8-buster
  stage: deploy
  before_script:
    - pip install -r requirements.txt
    - pip install git+https://$protected_material_token@github.com/squidfunk/mkdocs-material-insiders.git
  script:
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - changes:
        - docs/*