version: "3.9"
services:
  exit-node:
    env_file:
      - config.env
    build: .
    ports:
      - "5000:5000"
  lethean-cli:
    ports:
      - "48782:48782"
      - "48772:48772"
    image: "registry.gitlab.com/lethean.io/blockchain/lethean:latest"