version: "3.9"

services:
  blockchain:
    image: lthn/chain
    container_name: chain
  dispatcher:
    container_name: dispatcher
    build: .
    image: lthn/vpn
    links:
      - blockchain
    ports:
      - "5000:5000"
      - 14660:14660
    volumes:
      - ./settings:/home/lthn/vpn/etc:rw
volumes:
  data:
