site_name: Lethean VPN
site_url: https://vpn.lethean.help/
site_dir: public
copyright: Copyright &copy; Lethean.io Community
repo_url: https://gitlab.com/lthn.io/projects/vpn/node
edit_uri: edit/master/docs/
repo_name: lthn/vpn
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: docs/overrides
  favicon: images/favicon.ico
  language: en
  font:
    text: montserrat
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/letheanvpn
    - icon: fontawesome/brands/github
      link: https://github.com/lethean-io
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/lthn.io
  alternate:
    - name: English
      link: https://vpn.lethean.help/en/
      lang: en
    - name: Deutsch
      link: https://vpn.lethean.help/de/
      lang: de
    - name: Russian
      link: https://vpn.lethean.help/ru/
      lang: ru

plugins:
  - search:
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
        ru: Pусский
  - git-revision-date-localized:
       fallback_to_build_date: true
       enable_creation_date: true

markdown_extensions:
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ⚓︎